### PR TITLE
Walkthrough 2.0

### PR DESCRIPTION
**Pull request by wtrocki**
## Motivation

Purpose of this PR is to discuss and build new mobile walkthrough based on code ready and streamline collaboration on the walkthrough

## What we have now

1. Showcase is now represented as a single container build and tested by our team that is being used inside OpenShift template. We moved to this workflow to:

- Simplify the maintenance of the walkthrough (as this doubles number of steps)
- In many cases, we received issues with a walkthrough that were code ready specific. 

Moving to OpenShift 4.0 and using Eclipse Che will require significant changes in workflow.
Our walkthrough showcases data sync features 

2. As base now we will need to get showcase codebase into CodeReady.
Build client-side applications using the predefined command. Then build and deploy the server into node.js container. This container host both the ionic app and the server for simplicity and a smaller footprint. 

## Ideas

1. Go with building client and server applications and deploying it from scratch - which could be error-prone and cause some issues. The classical build app experience

2. Use base image that already has an app and then simply builds some very small layer on top of it that will contain small client modifications (configs etc.)

3. Hide fact that user code will be used in the deployment and deploy the predefined containers. This way if eclipe che steps will fail people will still be able to play with the app etc.

### CODE REVIEW

**Comment by wtrocki** [comment]
CC @darahayes @craicoverflow

**Comment by pwright** [comment]
@tiffanynolan are you aware of this PR?

**Comment by tiffanynolan** [comment]
Thanks for alerting me to this PR, @pwright. 

@wtrocki - It would be great to sync with you on this as there is some work in progress for getting this to work on OS4 and added to the standard, included SPs with RHMI for LA. Here's the doc I've been using: https://docs.google.com/document/d/1GOqCFwCExksYvy83vj6SdXWTk3yalTqrm2zsPo4fzP4/edit?ts=5dcf335b#heading=h.y9makewvm0gm

**Comment by tiffanynolan** [comment]
PS: I have a repo that I've been working on to work through all 5 of the SPs so I can quickly iterate. The plan is to move these to the Integreatly repo once I can get through these e2e at least once each.  https://github.com/tiffanynolan/solution-patterns

**Comment by wtrocki** [comment]
Update. This part of the walkthough will be dedicated to OpenShift 3.0. We will use separate repo for openshift 4.0 

https://github.com/integr8ly/solution-patterns/tree/master/walkthroughs/5-adding-data-sync-graphql

Huge thanks to @tiffanynolan for setting this up!

**Pull request closed without merging**
